<a href="https://colab.research.google.com/github/rajdepot/python_basics/blob/main/01_Basics_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer).

### Numpy vs Lists

In [ ]:
# intialise a list with the following elements: 1, 2, 3, 4, 5

my_list = [1, 2, 3, 4, 5]
# try to multiply 2.5 directly to the created list
my_list_new = 2.5*my_list


TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
import numpy as np

Procedural Concepts of Arrays

Declaration and Initialization

Declaration: Arrays in NumPy are declared using np.array().

Initialization: Allocating memory for the array, either with predefined values or zeros.

In [ ]:
list1 = [1,2,3,4,5]

In [ ]:
for i in list1:
    print(2.5*i)

2.5
5.0
7.5
10.0
12.5


In [ ]:
np_array = np.array([1,2,3,4,5])

In [ ]:
np_array

array([1, 2, 3, 4, 5])

In [ ]:
np_array_new = 2.5*np_array
print(np_array_new)

[ 2.5  5.   7.5 10.  12.5]


Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

### Creating NumPy Arrays

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known)

In [ ]:
arr1=np.ones(5)
arr1.shape

(5,)

In [ ]:
# # Create an array of 1s
# ones_array = np.ones(5)
# print("Ones Array:", ones_array)

Ones Array: [1. 1. 1. 1. 1.]


In [ ]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [ ]:

# Create an array of 0s
zeros_array = np.zeros(5)
print("Zeros Array:", zeros_array)



Zeros Array: [0. 0. 0. 0. 0.]


In [ ]:
arr2 = np.range(0,10,2)
print(arr2)
arr2.shape

AttributeError: module 'numpy' has no attribute 'range'

In [ ]:
arr2 = np.arange(0,10,2)
print(arr2)
arr2.shape

[0 2 4 6 8]


(5,)

In [ ]:
# Create an array with increments of fixed step size
## evenly spaced elements with a fixed step size
arange_array = np.arange(0, 1, 2)
print("Arange Array:", arange_array)


In [ ]:
# Create an array of fixed length
## evenly spaced n elements
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create a constant array of any number 'n'
full_array = np.full(10, 5)
print("Full Array:", full_array)


Full Array: [5 5 5 5 5 5 5 5 5 5]


In [ ]:
[1,2,3],[1,2,3],[1,2,3]

In [ ]:
x = np.array([1,2,3])
np.tile(x, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# Create a new array by repeating an existing array for a fixed number of times
original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, 3)
print("Tiled Array:", tiled_array)


Tiled Array: [1 2 3 1 2 3 1 2 3]


In [ ]:
# Create an identity matrix of any dimension
identity_matrix = np.eye(3, dtype='int')
print("Identity Matrix:\n", identity_matrix)



Identity Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
np.random.random

In [ ]:
# Create an array of random numbers between 0 and 1
random_array = np.random.random(3)
print("Random Array:", random_array)



Random Array: [0.90457171 0.48151762 0.42856468]


In [ ]:
np.random.rand(1)

array([0.10701794])

In [ ]:
# Create a random array of integers within a particular range
randint_array = np.random.randint(1, 10, size=(2, 3))
print("Random Integer Array:\n", randint_array)


TypeError: Unsupported dtype dtype('float64') for randint

### Converting list to arrays

In [ ]:
import numpy as np

#### Lists to Arrays


In [ ]:
# Convert a list to a NumPy array
my_list = [[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]
numpy_array_from_list = np.array(my_list)

print("List:", my_list)
print("NumPy Array:", numpy_array_from_list)
numpy_array_from_list.shape

List: [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
NumPy Array: [[1 2 3 4 5]
 [1 2 3 4 5]]


(2, 5)

#### Tuples to Arrays


In [ ]:
numpy_array_from_list[2]

IndexError: ignored

In [ ]:
# Convert a tuple to a NumPy array
my_tuple = (1, 2, 3, 4, 5)
numpy_array_from_tuple = np.array(my_tuple)

print("Tuple:", my_tuple)
print("NumPy Array:", numpy_array_from_tuple)


Tuple: (1, 2, 3, 4, 5)
NumPy Array: [1 2 3 4 5]


#### Initializing Arrays


In [ ]:
numpy_array_from_tuple.dtype

dtype('int64')

In [ ]:
fixed_size_array = np.ones(10, dtype="float")
fixed_size_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Initialize an array of fixed size with zeros
fixed_size_array = np.zeros(5, dtype=int)

print("Fixed Size Array (Zeros):", fixed_size_array)


Fixed Size Array (Zeros): [0 0 0 0 0]


#### Accessing Elements

In [ ]:
# Accessing individual elements using indexing
print("First element:", numpy_array_from_list[0])
print("Second element:", numpy_array_from_list[1])


First element: [1 2 3 4 5]
Second element: [1 2 3 4 5]


#### Iterating Through Arrays

In [ ]:
lst1 = [1,2,3]


In [ ]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
for i in arr1:
    print(i)

1
2
3
4
5


In [ ]:
arr1%2

array([1, 0, 1, 0, 1])

#### Slicing

In [ ]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
print(arr1)


[1 2 3 4 5]


In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1[1:2]

array([2])

In [ ]:
arr1[-3:-2]

array([3])

In [ ]:
# Slicing to get a subset of elements
subset = arr1[1:4]
print("Subset:", subset)


Subset: [2 3 4]


In [ ]:
import numpy as np

# Create a 1-dimensional NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



In [ ]:
# Example 1: Basic Slicing
slice1 = original_array[2:6]
print("Slice 1 (Basic Slicing):", slice1)


Slice 1 (Basic Slicing): [3 4 5 6]


In [ ]:
# Example 2: Using colon to select a range
slice2 = original_array[1:8:2]
print("\nSlice 2 (Selecting Every Second Element):", slice2)



Slice 2 (Selecting Every Second Element): [2 4 6 8]


In [ ]:
# Example 3: Negative indices for backward slicing
slice3 = original_array[-5:-1]
print("\nSlice 3 (Negative Indices):", slice3)



Slice 3 (Negative Indices): [5 6 7 8]


In [ ]:
original_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Example 4: Omitting start or end index
slice4 = original_array[:5]
print("\nSlice 4 (Omitting Start Index):", slice4)



Slice 4 (Omitting Start Index): [1 2 3 4 5]


In [ ]:
original_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Example 5: Conditional Slicing
condition = original_array > 5
slice5 = original_array[condition]
print("\nSlice 5 (Conditional Slicing):", slice5)



Slice 5 (Conditional Slicing): [6 7 8 9]


#### Contents of Array

In [ ]:
numpy_array_from_list

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
# Print array shape, size, and data type
print("Shape:", numpy_array_from_list.shape)
print("Size:", numpy_array_from_list.size)
print("Data Type:", numpy_array_from_list.dtype)


Shape: (2, 5)
Size: 10
Data Type: int64


#### Creating large arrays

In [ ]:
# Creating a large NumPy array
large_array = np.random.random((1000, 1000))

# Inspecting structure
print("Shape:", large_array.shape)
print("Size:", large_array.size)
print("Data Type:", large_array.dtype)


Shape: (1000, 1000)
Size: 1000000
Data Type: float64


In [ ]:
np.sin(0.523599)

0.5000001943375613

In [ ]:
np.cos(0.523599)

0.8660252915835662

In [ ]:
np.tan(0.785398)

0.9999996732051568

In [ ]:
oa=np.array([1,2,3,4,5,6,7,8,9])
s=oa[2:6]
print("S",s)
print(s)

S [3 4 5 6]
[3 4 5 6]


In [ ]:
a= 2
b= 3


In [ ]:
print(a)
print(b)

2
3


### Reshape

In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8])

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1.shape

(8,)

In [ ]:
arr_reshaped = arr1.reshape(4,2)

In [ ]:
arr_reshaped.shape

(4, 2)

In [ ]:
arr_reshaped

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a = 2

In [ ]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
dir(dict)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']