<a href="https://colab.research.google.com/github/rajdepot/python_basics/blob/main/04_Numpy_Operations_and_Practice_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from PIL import Image
import numpy as np


# load the image and convert into
# numpy array
img = Image.open('gettyimages-147786673.jpg')



In [ ]:
# img

In [ ]:
# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = np.asarray(img)
numpydata

array([[[ 54,  70,  59],
        [ 57,  73,  62],
        [ 55,  71,  60],
        ...,
        [ 45,  63,  23],
        [ 44,  62,  22],
        [ 40,  58,  18]],

       [[ 57,  73,  62],
        [ 59,  75,  64],
        [ 57,  73,  62],
        ...,
        [ 40,  58,  18],
        [ 39,  57,  17],
        [ 35,  53,  13]],

       [[ 57,  73,  62],
        [ 58,  74,  63],
        [ 56,  72,  61],
        ...,
        [ 38,  56,  16],
        [ 37,  55,  15],
        [ 34,  52,  12]],

       ...,

       [[174, 202, 154],
        [175, 203, 155],
        [176, 204, 156],
        ...,
        [152, 184, 108],
        [152, 184, 108],
        [152, 184, 108]],

       [[174, 202, 153],
        [175, 203, 154],
        [175, 203, 154],
        ...,
        [153, 185, 109],
        [153, 185, 109],
        [153, 185, 109]],

       [[173, 201, 152],
        [174, 202, 153],
        [175, 203, 152],
        ...,
        [154, 186, 110],
        [154, 186, 110],
        [154, 186, 110]]

In [ ]:
numpydata.shape

(1470, 980, 3)

In [ ]:
# <class 'numpy.ndarray'>
print(type(numpydata))

#  shape
print(numpydata.shape)

<class 'numpy.ndarray'>
(1470, 980, 3)


In [ ]:
## Q1 - find non zero elements

In [ ]:
arr1 = np.array([0,1,2,3,4])
np.count_nonzero(arr1)

4

In [ ]:
## Q2 - reverse the array

In [ ]:
arr1 = np.array([0,1,2,3,4])
np.flip(arr1)

array([4, 3, 2, 1, 0])

In [ ]:
## Q3 : Given a numpy array and a list, find which elements from the list are present in the array
#

In [ ]:
arr1 = np.array([0,1,2,3,4])
list1 = [1,2,3]
np.isin(arr1,list1)
# arr1[1:4]

array([False,  True,  True,  True, False])

In [ ]:
## Q4 - given an integer x and an numpy array, Get row numbers of NumPy array having element larger than X,
# if Arr = [[1,2,3,4,5],
#       [10,-3,30,4,5],
#       [3,2,5,-4,5],
#       [9,7,3,6,5]]
# and X = 6 then output is [ 1, 3 ] because row 1 and row 3 has elements greater than 6



In [ ]:
arr1 = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

In [ ]:
x = 6

In [ ]:
# np.where(arr1>6)

(array([1, 1, 3, 3]), array([0, 2, 0, 1]))

In [ ]:
arr1 = np.array([1,2,3])
np.where(arr1>1, 1, 0)

array([0, 1, 1])

In [ ]:
np.any(arr1>2)

True

In [ ]:
np.any(arr1>x,axis=1)

array([False,  True, False,  True])

In [ ]:
np.where((True, False, True))

(array([0, 2]),)

In [ ]:
np.where

In [ ]:
output = np.where(np.any(arr1>x,axis=1))[0]
print(output)

[1 3]


In [ ]:
##q5  Given a numpy array, Find indices of elements which are 0

In [ ]:
arr1 = np.array([1,2,0,8,9,0,4])
x = np.where(arr1==0)

In [ ]:
x

(array([2, 5]),)

In [ ]:
print(x[0])

[2 5]


In [ ]:
arr1 ==0

array([False, False,  True, False, False,  True, False])

In [ ]:
## q6 - given a numpy array, trim the leading Zeroes ,
## eg- if input is [0,0,1,2,3] output should be [1,2,3]

In [ ]:
x = np.array([0,0,1,2,3,0,0])
np.trim_zeros(x, trim='fb')

array([1, 2, 3])

In [ ]:
# axis = 1 operations along columns, Operations are performed along the columns (horizontally).
# axis = 0 operations along rows, Operations are performed along the rows (vertically).

In [ ]:
## Q7
# ### Given a 2d array.
x = np.array([[1,2],[3,4]])
1. find the sum of all the elements [output=  10]
2. find the sum of all the elements in each row [output = [3, 7]]
3. find the sum of all the elements in each columns [output = [4, 6]]

In [ ]:
x.sum()

10

In [ ]:
x.sum(axis=1)

array([3, 7])

In [ ]:
x.sum(axis=0)

array([4, 6])

In [ ]:
## Q8
## given two arrays carry out the element wise additions
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
# output should be [5,7,9]
output = arr1 +arr2
print(output)

[5 7 9]


In [ ]:
## Q9
# Calculate the dot product of two NumPy arrays [1, 2, 3] and [4, 5, 6].
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# output should be 32 (1*4+ 2*5 + 3*6)
output = np.dot(x,y)
print(output)

32


In [ ]:
## Q10
Consider the following NumPy array:
grades = np.array([92, 85, 76, 88, 95, 90, 84, 78, 80, 82])
Use np.where to create a new array called pass_fail such that:
- If the grade is greater than or equal to 85, assign 'Pass'.
- If the grade is less than 85, assign 'Fail'.
- Count the number of 'Pass' and 'Fail' grades.
output
Number of Pass grades: 5
Number of Fail grades: 5

In [ ]:
grades = np.array([92, 85, 76, 88, 95, 90, 84, 78, 80, 82])
grades_array = np.where(grades>=85, "Pass", "Fail")

In [ ]:
pass_students = np.sum(grades_array=="Pass")
fail_students = np.sum(grades_array=="Fail")
print(pass_students,fail_students )

5 5
